# Generated by Django 3.0.3 on 2020-02-04 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeyWord',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('key_word', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='key_words',
            field=models.ManyToManyField(blank=True, to='my_blog.KeyWord'),
        ),
    ]
